# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_install_hook_types: [pre-commit,commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff # Runs ruff linter (replaces flake8)
        args: [--fix, --exit-non-zero-on-fix] # --fix for fixing errors
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML]

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.2.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell

  - repo: https://github.com/espressif/check-copyright/
    rev: v1.1.0
    hooks:
      - id: check-copyright
        args: ['--config', 'check_copyright_config.yaml']
